networks:
  rhtas:
    name: "rhtas"

services:
  rhtas-console:
    image: localhost/devcontainer-rhtas-console:latest
    build:
      dockerfile: ./Dockerfile
    security_opt:
      - "label=disable"
    userns_mode: "keep-id"
    # For development, the container just sleeps and you run the console manually with:
    # ./bin/rhtas_console --tuf-repo-url="https://tuf-repo-cdn.sigstore.dev"
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:cached
    networks:
      - rhtas
